version: '3.8'

services:
  server:
    image: bonekee/weather-reporter-service-server:latest
    container_name: weather-server
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

