---
- name: Run weather-service
  hosts: all
  become: yes

  vars:
    docker_compose_file: "/opt/docker-compose.yml"
    
  tasks:
    - name: Install dependencies for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository to the system
      command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

    - name: Install Docker
      yum:
        name:
          - docker-ce
        state: latest

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose.yml file to the server
      copy:
        src: resources/docker-compose.yaml
        dest: "{{ docker_compose_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Start the application using docker-compose
      command: "docker compose -f {{ docker_compose_file }} up -d"

    - name: Verify that containers are running
      command: "docker ps"
      register: docker_ps_output

    - name: Output the result of docker ps command
      debug:
        msg: "{{ docker_ps_output.stdout }}"
